#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'ntp', '1.3.2'
cookbook 'openssh', '1.1.4'
cookbook 'apt', '1.7.0'
cookbook 'yum', '2.1.0'
cookbook 'build-essential', '1.3.4'
cookbook 'erlang', '1.2.0'
cookbook 'openssl', '1.0.2'
cookbook 'postgresql', '2.2.2'
cookbook 'aws', '0.100.6'
cookbook 'xfs', '1.1.0'
cookbook 'database', '1.3.12'
cookbook 'mysql', '2.1.2'
cookbook 'apache2', '1.6.0'
cookbook 'selinux', '0.5.6'

cookbook 'rabbitmq',
  :git => "git://github.com/opscode-cookbooks/rabbitmq.git"

cookbook 'sysctl',
  :git => 'https://github.com/rcbops-cookbooks/sysctl.git'

cookbook 'osops-utils',
  :git => 'https://github.com/rcbops-cookbooks/osops-utils.git'

cookbook 'keepalived',
  :git => 'https://github.com/rcbops-cookbooks/keepalived.git'

cookbook 'rsyslog',
  :git => 'git://github.com/rcbops-cookbooks/rsyslog.git'

cookbook 'monit',
  :git => 'https://github.com/rcbops-cookbooks/monit.git'

cookbook 'collectd',
  :git => 'https://github.com/achied/collectd.git',
  :ref => "experimental"

cookbook 'collectd-plugins',
  :git => 'https://github.com/rcbops-cookbooks/collectd-plugins.git'

cookbook 'monitoring',
  :git => 'https://github.com/rcbops-cookbooks/monitoring.git'

cookbook 'dsh',
  :git => 'https://github.com/rcbops-cookbooks/dsh.git'

cookbook 'rabbitmq-openstack',
  :git => 'https://github.com/rcbops-cookbooks/rabbitmq-openstack.git'

cookbook 'mysql-openstack',
  :git => 'https://github.com/achied/mysql-openstack.git',
  :ref => 'experimental'

cookbook 'keystone',
  :git => 'https://github.com/rcbops-cookbooks/keystone.git'

cookbook 'glance',
  :git => 'https://github.com/rcbops-cookbooks/glance.git'

cookbook 'cinder',
  :git => 'https://github.com/rcbops-cookbooks/cinder.git'

cookbook 'nova',
  :git => 'https://github.com/rcbops-cookbooks/nova.git'

cookbook 'nova-network',
  :git => 'https://github.com/achied/nova-network.git',
  :ref => 'experimental'

cookbook 'horizon',
  :git => 'https://github.com/rcbops-cookbooks/horizon.git'


# cookbook 'swift',
#   :git => 'https://github.com/mattray/swift.git',
#   :ref => 'essex'
